"""initial

Revision ID: ba061be8231b
Revises: 
Create Date: 2026-07-27 14:22:36.500630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba061be8231b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('draft_round', sa.Integer(), nullable=True),
    sa.Column('draft_number', sa.Integer(), nullable=True),
    sa.Column('nba_years', sa.Integer(), nullable=True, comment='Years in NBA'),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_table('seasons',
    sa.Column('season_id', sa.String(length=10), nullable=False, comment='e.g., 2023-24'),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('regular_season_games', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('arena', sa.String(length=200), nullable=True),
    sa.Column('conference', sa.String(length=20), nullable=True, comment='East/West'),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_index(op.f('ix_teams_full_name'), 'teams', ['full_name'], unique=False)
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=20), nullable=False, comment='Regular Season / Playoffs / Finals'),
    sa.Column('playoff_round', sa.String(length=50), nullable=True, comment='First Round, Conference Semis, Conference Finals, Finals'),
    sa.Column('arena', sa.String(length=200), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_game_type'), 'games', ['game_type'], unique=False)
    op.create_index(op.f('ix_games_season_id'), 'games', ['season_id'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.String(length=10), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('minutes_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('points_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rebounds_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assists_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('steals_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blocks_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('turnovers_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('field_goal_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('three_point_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('free_throw_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('player_efficiency_rating', sa.Numeric(precision=5, scale=2), nullable=True, comment='PER'),
    sa.Column('true_shooting_pct', sa.Numeric(precision=5, scale=4), nullable=True, comment='TS%'),
    sa.Column('usage_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='USG%'),
    sa.Column('offensive_rating', sa.Numeric(precision=5, scale=2), nullable=True, comment='ORtg'),
    sa.Column('defensive_rating', sa.Numeric(precision=5, scale=2), nullable=True, comment='DRtg'),
    sa.Column('win_shares', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('box_plus_minus', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('value_over_replacement_player', sa.Numeric(precision=5, scale=2), nullable=True, comment='VORP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'player_id', 'team_id', name='uq_season_player_team')
    )
    op.create_index(op.f('ix_player_season_stats_player_id'), 'player_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_season_id'), 'player_season_stats', ['season_id'], unique=False)
    op.create_table('playoff_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.String(length=10), nullable=False),
    sa.Column('round', sa.String(length=50), nullable=False, comment='First Round, Conference Semis, Conference Finals, Finals'),
    sa.Column('series_number', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_wins', sa.Integer(), nullable=True),
    sa.Column('away_team_wins', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'round', 'series_number', name='uq_season_round_series')
    )
    op.create_index(op.f('ix_playoff_series_season_id'), 'playoff_series', ['season_id'], unique=False)
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.String(length=10), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('win_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('points_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('points_allowed_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('field_goal_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('three_point_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('free_throw_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rebounds_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assists_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('steals_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blocks_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conference_rank', sa.Integer(), nullable=True),
    sa.Column('division_rank', sa.Integer(), nullable=True),
    sa.Column('playoff_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'team_id', name='uq_season_team')
    )
    op.create_index(op.f('ix_team_season_stats_season_id'), 'team_season_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_season_stats_team_id'), 'team_season_stats', ['team_id'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=True),
    sa.Column('minutes_played', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds_total', sa.Integer(), nullable=True),
    sa.Column('rebounds_offensive', sa.Integer(), nullable=True),
    sa.Column('rebounds_defensive', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('personal_fouls', sa.Integer(), nullable=True),
    sa.Column('field_goals_made', sa.Integer(), nullable=True),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=True),
    sa.Column('three_pointers_made', sa.Integer(), nullable=True),
    sa.Column('three_pointers_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('efficiency_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game')
    )
    op.create_index(op.f('ix_player_game_stats_game_id'), 'player_game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_player_id'), 'player_game_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_game_stats_player_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_game_id'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index(op.f('ix_team_season_stats_team_id'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_season_id'), table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index(op.f('ix_playoff_series_season_id'), table_name='playoff_series')
    op.drop_table('playoff_series')
    op.drop_index(op.f('ix_player_season_stats_season_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_player_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_games_season_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_type'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_full_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
